// <auto-generated />
using System;
using ApiV2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250411141259_UpdateTablesShoppingListAndLines")]
    partial class UpdateTablesShoppingListAndLines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MesCoursesApi.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Pomme"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Banane"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Carotte"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Brocoli"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "Poulet"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Boeuf"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Name = "Lait"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Name = "Yaourt"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Name = "Riz"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Name = "Pâtes"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            Name = "Sel"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            Name = "Poivre"
                        });
                });

            modelBuilder.Entity("MesCoursesApi.Models.IngredientCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IngredientCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Légumes"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Viandes"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Produits laitiers"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Céréales"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Épices"
                        });
                });

            modelBuilder.Entity("MesCoursesApi.Models.ShoppingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ShoppingLists");
                });

            modelBuilder.Entity("MesCoursesApi.Models.ShoppingListLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ShoppingListId")
                        .HasColumnType("integer");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("ShoppingListLines");
                });

            modelBuilder.Entity("MesCoursesApi.Models.Ingredient", b =>
                {
                    b.HasOne("MesCoursesApi.Models.IngredientCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MesCoursesApi.Models.ShoppingListLine", b =>
                {
                    b.HasOne("MesCoursesApi.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MesCoursesApi.Models.ShoppingList", "ShoppingList")
                        .WithMany("Lines")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("MesCoursesApi.Models.ShoppingList", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
